// Generated by scripts/sculpture.mjs. Do not edit by hand.
export const sculpture = {
  "width": 1600,
  "height": 1187,
  "back": "/hero/ribbon-back.69c30568.webp",
  "front": "/hero/ribbon-front.b74523e4.webp"
} as const;
